### ISSUE TITLE
Issue with twig-pack installation by Composer

### ISSUE THREAD

**Issue by CelineViala** [symfony/twig-pack#1]
Hi,
When I try to install this package, it doesn't  work. The installation starts normally but at the end of the processus the pack is removed without any error message:

```
 composer require symfony/twig-pack
Using version ^1.0 for symfony/twig-pack
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.4.*"
Package operations: 1 install, 0 updates, 0 removals
  - Installing symfony/twig-pack (v1.0.0): Loading from cache
Writing lock file
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class

Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear [OK]
Executing script assets:install public [OK]

Unpacked symfony/twig-pack dependencies
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 0 installs, 0 updates, 1 removal
  - Removing symfony/twig-pack (v1.0.0)
```

How fix out that ??

**Comment by nicolas-grekas** [comment]
can you check if you're using the latest version of flex? It should be 1.9.6

**Comment by CelineViala** [comment]
Yes I'm using the 1.9.6 version of symfony/flex

**Comment by nicolas-grekas** [comment]
I suppose you already have twig installed, don't you?
If yes, then the behavior is expected since https://github.com/symfony/flex/pull/655: packs are auto-unpacked, then removed.

**Comment by CelineViala** [comment]
Yes Twig is already installed... So actually,  all is allright??

**Comment by nicolas-grekas** [comment]
Yep, no issue here.

**Comment by xf-** [comment]
@nicolas-grekasi had the same issue and path and that caused the error, but based on documentation I thought I need this package. I tried to install it, but it was removed.

This plus https://github.com/symfony/symfony/issues/37439 was the solution for me.

Documentation
https://symfony.com/doc/current/controller/error_pages.html#overriding-the-default-error-templates
