### ISSUE TITLE
Problem with composer require the pack

### ISSUE THREAD

**Issue by hubertoLEMP** [symfony/twig-pack#3]
Hi @fabpot and @nicolas-grekas,

first of all thanks for your great work on symfony! 

I read this article:
https://symfony.com/doc/current/controller/error_pages.html

If I run: composer require symfony/twig-pack

The twig-pack will be install and automatically removed - without any visible errors:
`
php composer.phar require symfony/twig-pack --with-all-dependencies
Using version ^1.0 for symfony/twig-pack
./composer.json has been updated
Running composer update symfony/twig-pack --with-all-dependencies
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "5.3.*"
Updating dependencies
Lock file operations: 1 install, 7 updates, 0 removals
  - Upgrading symfony/cache (v5.3.4 => v5.3.7)
  - Upgrading symfony/dependency-injection (v5.3.4 => v5.3.7)
  - Upgrading symfony/finder (v5.3.4 => v5.3.7)
  - Upgrading symfony/framework-bundle (v5.3.4 => v5.3.7)
  - Upgrading symfony/mime (v5.3.4 => v5.3.7)
  - Upgrading symfony/routing (v5.3.4 => v5.3.7)
  - Locking symfony/twig-pack (v1.0.1)
  - Upgrading symfony/var-exporter (v5.3.4 => v5.3.7)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 7 updates, 0 removals
  - Downloading symfony/routing (v5.3.7)
  - Downloading symfony/finder (v5.3.7)
  - Downloading symfony/dependency-injection (v5.3.7)
  - Downloading symfony/var-exporter (v5.3.7)
  - Downloading symfony/cache (v5.3.7)
  - Downloading symfony/framework-bundle (v5.3.7)
  - Downloading symfony/mime (v5.3.7)
  - Upgrading symfony/routing (v5.3.4 => v5.3.7): Extracting archive
  - Upgrading symfony/finder (v5.3.4 => v5.3.7): Extracting archive
  - Upgrading symfony/dependency-injection (v5.3.4 => v5.3.7): Extracting archive
  - Upgrading symfony/var-exporter (v5.3.4 => v5.3.7): Extracting archive
  - Upgrading symfony/cache (v5.3.4 => v5.3.7): Extracting archive
  - Upgrading symfony/framework-bundle (v5.3.4 => v5.3.7): Extracting archive
  - Upgrading symfony/mime (v5.3.4 => v5.3.7): Extracting archive
  - Installing symfony/twig-pack (v1.0.1): Extracting archive
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
13 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Run composer recipes at any time to see the status of your Symfony recipes.

Unpacking Symfony packs
  - Unpacked symfony/twig-pack
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 0 updates, 1 removal
  - Removing symfony/twig-pack (v1.0.1)
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
12 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear [OK]
Executing script assets:install public [OK]
`

Why does this happen? I can't find something useful on google for this problem.

If I look in the repo, there is only a composer and LICENSE file is that right?
https://github.com/symfony/twig-pack

Can you help me please?

Best Regards
Huberto

**Comment by arcticlinux** [comment]
Similar to webpack-encore-pack

> Flex now forces all packs to be unpacked
> https://github.com/symfony/symfony/issues/42706#issuecomment-904730127

So twig-pack has been replaced by twig-bundle

See also:
http://fabien.potencier.org/symfony4-unpack-the-packs.html
https://github.com/symfony/symfony/discussions/42700

**Comment by nicolas-grekas** [comment]
That's the expected behavior yes: packs are unpacked, and removed.

**Comment by jgauthi** [comment]
But one of the advantages of the packs is to simplify the maintenance of the composer.json by merging several libraries according to their usefulness. Instead, the composer.json got big... (I was using twig-pack, debug-pack and orm-pack).

**Comment by nicolas-grekas** [comment]
If you want to install group of deps and manage them as a group, you can create a composer metapackage. Packs are another kind of grouped deps that are unpacked. Their advantage is that they give back control of individual packages in the group to the user. Each kind its purpose.
